export const TITHI_NAMES = [
  "Pratipada",
  "Dvitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Purnima",
  "Pratipada",
  "Dvitiya",
  "Tritiya",
  "Chaturthi",
  "Panchami",
  "Shashthi",
  "Saptami",
  "Ashtami",
  "Navami",
  "Dashami",
  "Ekadashi",
  "Dwadashi",
  "Trayodashi",
  "Chaturdashi",
  "Amavasya",
];

export const NAKSHATRA_NAMES = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];
export const NAKSHATRA_LORDS = [
  "Ketu",
  "Venus",
  "Sun",
  "Moon",
  "Mars",
  "Rahu",
  "Jupiter",
  "Saturn",
  "Mercury",
];

export const YOGA_NAMES = [
  "Vishkambha",
  "Priti",
  "Ayushman",
  "Saubhagya",
  "Shobhana",
  "Atiganda",
  "Sukarman",
  "Dhriti",
  "Shoola",
  "Ganda",
  "Vriddhi",
  "Dhruva",
  "Vyaghata",
  "Harshana",
  "Vajra",
  "Siddhi",
  "Vyatipata",
  "Variyana",
  "Parigha",
  "Shiva",
  "Siddha",
  "Sadhya",
  "Shubha",
  "Shukla",
  "Brahma",
  "Indra",
  "Vaidhriti",
];

export const KARANA_NAMES = [
  "Bava",
  "Balava",
  "Kaulava",
  "Taitila",
  "Garaja",
  "Vanija",
  "Vishti",
  "Bava",
  "Balava",
  "Kaulava",
];

export const RASHI_NAMES = [
  "Mesha",
  "Vrishabha",
  "Mithuna",
  "Karka",
  "Simha",
  "Kanya",
  "Tula",
  "Vrishchika",
  "Dhanu",
  "Makara",
  "Kumbha",
  "Meena",
];
export const rashiNames = [
  "Mesh",
  "Vrishabh",
  "Mithun",
  "Karka",
  "Simha",
  "Kanya",
  "Tula",
  "Vrishchik",
  "Dhanu",
  "Makar",
  "Kumbha",
  "Meen",
];

export const rashiLords = [
  "Mars",
  "Venus",
  "Mercury",
  "Moon",
  "Sun",
  "Mercury",
  "Venus",
  "Mars",
  "Jupiter",
  "Saturn",
  "Saturn",
  "Jupiter",
];

export const gana = ["Deva", "Manushya", "Rakshasa"];

export const nadi = ["Aadi", "Madhya", "Antya"];

export const yoni = [
  "Horse",
  "Elephant",
  "Sheep",
  "Serpent",
  "Dog",
  "Cat",
  "Rat",
  "Cow",
  "Buffalo",
  "Tiger",
  "Deer",
  "Monkey",
];
export const weekdayNames = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const weekdayGhatak = {
  Sunday: "East",
  Monday: "South",
  Tuesday: "West",
  Wednesday: "North",
  Thursday: "North-East",
  Friday: "South-East",
  Saturday: "South-West",
};

export const DASHA_SEQUENCE = [
  { planet: "Ketu", years: 7 },
  { planet: "Venus", years: 20 },
  { planet: "Sun", years: 6 },
  { planet: "Moon", years: 10 },
  { planet: "Mars", years: 7 },
  { planet: "Rahu", years: 18 },
  { planet: "Jupiter", years: 16 },
  { planet: "Saturn", years: 19 },
  { planet: "Mercury", years: 17 },
];
export const days = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
export const PLANETS = [
  {
    name: "Sun",
    id: 0,
    exhalted: 1,
    debiliated: 7,
    friendsRashi: [4, 1, 8, 3, 6, 9, 12],
    enemyRashi: [2, 7, 10, 11],
    neutrlRashi: [],
    ownRashi: [5],
    drushti: [6],
  },
  {
    name: "Moon",
    id: 1,
    exhalted: 2,
    debiliated: 8,
    friendsRashi: [5, 1, 8, 9, 12],
    enemyRashi: [3, 6, 2, 7, 10, 11],
    neutrlRashi: [],
    ownRashi: [4],
    drushti: [6],
  },
  {
    name: "Mars",
    id: 4,
    exhalted: 10,
    debiliated: 4,
    friendsRashi: [5, 9, 12],
    enemyRashi: [10, 11],
    neutrlRashi: [3, 6, 4, 2, 8],
    ownRashi: [1, 8],
    drushti: [3, 6, 7],
  },
  {
    name: "Mercury",
    id: 2,
    exhalted: 6,
    debiliated: 12,
    friendsRashi: [4, 2, 7, 10, 11],
    enemyRashi: [1, 8, 9, 12, 10, 11],
    neutrlRashi: [5],
    ownRashi: [3, 6],
    drushti: [6],
  },
  {
    name: "Jupiter",
    id: 5,
    exhalted: 4,
    debiliated: 10,
    friendsRashi: [5, 1, 8],
    enemyRashi: [],
    neutrlRashi: [4, 3, 6, 2, 7, 10, 11],
    ownRashi: [9, 12],
    drushti: [4, 6, 8],
  },
  {
    name: "Venus",
    id: 3,
    exhalted: 12,
    debiliated: 6,
    friendsRashi: [3, 6, 10, 11],
    enemyRashi: [5, 9, 12],
    neutrlRashi: [4, 1, 8],
    ownRashi: [2, 7],
    drushti: [6],
  },
  {
    name: "Saturn",
    id: 6,
    exhalted: 7,
    debiliated: 1,
    friendsRashi: [2, 7],
    enemyRashi: [5],
    neutrlRashi: [4, 1, 8, 3, 6, 9, 12],
    ownRashi: [10, 11],
    drushti: [2, 6, 9],
  },
  {
    name: "Rahu",
    id: 10,
    exhalted: 2,
    debiliated: 8,
    friendsRashi: [2, 7, 10, 11],
    enemyRashi: [4, 5, 1, 8],
    neutrlRashi: [3, 6, 9, 12],
    ownRashi: [],
    drushti: [4, 6, 8],
  },
  {
    name: "Ketu",
    id: 11,
    exhalted: 8,
    debiliated: 2,
    friendsRashi: [1, 8, 2, 7],
    enemyRashi: [4, 5, 10, 11],
    neutrlRashi: [3, 6, 9, 12],
    ownRashi: [],
    drushti: [4, 6, 8],
  },
];

export const PLANET_Avastha = [
  { avastha: "Bal", deg: 6 },
  { avastha: "Kumar", deg: 12 },
  { avastha: "Yuva", deg: 18 },
  { avastha: "Vrudha", deg: 24 },
  { avastha: "Mrit", deg: 30 },
];
export const VARNA_Scores = {
  1: "Kshatriya",
  2: "Vaishya",
  3: "Shudra",
  4: "Brahmin",
  5: "Kshatriya",
  6: "Vaishya",
  7: "Shudra",
  8: "Brahmin",
  9: "Kshatriya",
  10: "Vaishya",
  11: "Shudra",
  12: "Brahmin",
};

export const FRIENDS = {
  Sun: ["Moon", "Mars", "Jupiter"],
  Moon: ["Sun", "Mercury"],
  Mars: ["Sun", "Moon", "Jupiter"],
  Mercury: ["Sun", "Venus"],
  Jupiter: ["Sun", "Moon", "Mars"],
  Venus: ["Mercury", "Saturn"],
  Saturn: ["Mercury", "Venus"],
};
